[package]
name = "street-smarts-patterns"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
street-smarts-core = { workspace = true }

[dev-dependencies]
street-smarts-opinions = { path = "../street-smarts-opinions" }
street-smarts-conflict = { path = "../street-smarts-conflict" }
