//! # street-smarts-patterns
//!
//! Pattern operators that take a parcel (or a whole neighborhood) and
//! return a transformed neighborhood as a *proposal*.
//!
//! Per the spec: a proposal generated by this crate is one more opinion —
//! the opinion of an algorithm encoding an Alexander pattern. It is NOT
//! "the" answer, and the UI marks every generated output as such.
//!
//! v0.1 ships one operator: P95 Building Complex, applied to a single parcel.

#![forbid(unsafe_code)]

pub mod block_grouping;
pub mod building_shape;
pub mod parameters;
pub mod path_network;
pub mod planar;
pub mod prng;
pub mod p29_density_rings;
pub mod p37_house_cluster;
pub mod p95_building_complex;
pub mod p96_number_of_stories;
pub mod p107_wings_of_light;
pub mod p61_small_public_squares;
pub mod pipeline;
pub mod registry;
pub mod subdivision;

pub use parameters::{NoParams, ParamSpec, Parameters};
pub use registry::{available_operators, run_operator, OperatorInfo};
pub use subdivision::{apply_subdivision, DynOperator, PatternOperator, Subdivision, SubdivisionTrace};
